### ISSUE TITLE
Is there a plan to add some extra bundled index wrappers?

### ISSUE THREAD

**Issue by JimChengLin** [wangtzh/pibench#22]
The project is valuable. But it seems quite hard for a newbie(like me) to collect and compile some state-of-the-art PM index correctly. It would be great to have a few bundled index wrappers, then I can do a fast and meaningful comparison. Is there a license issue or whatsoever?

**Comment by wangtzh** [comment]
For the trees we tested in our earlier paper [1], it's mainly copyright issues (SAP's implementation of FPTree, NV-Tree and wbTree). For BzTree we have open sourced our implementation [1] with a PiBench wrapper. 

We are adding another wrapper for LevelDB [3]. So far these are the only two freely-available choices. But as long as you have access to some index, writing a wrapper is fairly simple (basically mechanically call the insert/delete/update/read/scan functions). We will contribute wrappers for a new NVM hash table design soon.

[1] http://www.vldb.org/pvldb/vol13/p574-lersch.pdf
[2] https://github.com/wangtzh/bztree
[3] https://github.com/wangtzh/pibench/pull/20
